trigger:
  branches:
    include:
      - main
      - dev

pool:
  name: 'Default'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'
    shell: cmd

  - script: npm run lint
    displayName: 'Run ESLint and Prettier'
    shell: cmd

  - script: npm run test -- --ci --coverage
    displayName: 'Run tests'
    shell: cmd

  - script: npm run build
    displayName: 'Build Next.js application'
    shell: cmd
