trigger:
  branches:
    include:
      - main
      - dev

pool:
  name: 'Default'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      command: 'ci'

  - task: Npm@1
    displayName: 'Run ESLint and Prettier'
    inputs:
      command: 'custom'
      customCommand: 'run lint'

  - task: Npm@1
    displayName: 'Run tests'
    inputs:
      command: 'test'
      arguments: '-- --ci --coverage'

  - task: Npm@1
    displayName: 'Build Next.js application'
    inputs:
      command: 'custom'
      customCommand: 'run build'
