trigger:
  branches:
    include:
      - main
      - dev

pool:
  name: 'Default'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: CmdLine@2
    displayName: 'Install dependencies'
    inputs:
      script: 'npm ci'

  - task: CmdLine@2
    displayName: 'Run ESLint and Prettier'
    inputs:
      script: 'npm run lint'

  - task: CmdLine@2
    displayName: 'Run tests'
    inputs:
      script: 'npm run test -- --ci --coverage'

  - task: CmdLine@2
    displayName: 'Build Next.js application'
    inputs:
      script: 'npm run build'
